name: JFrog upload

on: # Event
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test: # Job id
    runs-on: ubuntu-latest # Runner
    steps:
      - uses: actions/checkout@v2 # Step
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Jar
        run: ./gradlew build
      - name: Check Jar
        run: ls ./build/libs/
      - name: jForog Cli Official
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.RT_TOKEN }}
      - run: |
          jfrog rt ping
      - name: jFrog CLI for Artifactory
        uses: advancedcsg-open/action-jfrog-cli@v1.2.0
        with:
          url: 'https://opensourceenv.jfrog.io/artifactory/'
          credentials type: 'username'
          user: ${{ secrets.RT_USER }}
          password: ${{ secrets.RT_PASSWORD }}
          args: u "./build/libs/opensourceenv-1.0-SNAPSHOT.jar" "mu/sampleRepo/opensourceenv/" --recursive=false --build-name=opensourceenvBuildName

